version: "3.5"
services:
  caddy:
    image: caddy
    container_name: caddy-fastfood
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - external
      - common
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
      - PROJECT_NAME=${PROJECT_NAME}
      - PORT=${PORT}

  static:
    container_name: fastfood-static
    image: fastfood-static
    command: npm start
    restart: always
    build: .
    volumes:
      - ./src:/fastfood-static/src
    ports:
      - "3001:3000"
    networks:
      - common

networks:
  external:
  common:
    internal: true
    name: ${COMMON_NETWORK_NAME}-common-network
